UAF-259 EDS Modification for UAIdentityManagementPersonDocument changed from OJB to JPA
ua-eas/ksd-kc5.2.1-rice pull request #51
Opened 2017-08-15 03:37 UTC by amandazhangm

1. Moved UA IdentityMangementPersonDocument cutomized Java and xml from kim-impl and kim-ldap to rice-impl to align with vanilla IdentityMangementPersonDocument directory and jar build.
2. Since OJB is no longer used for rice-impl by rice, got to redefine UAIdentityManagementPersonDocument entity inheritance with EclipseLink JPA with details below. 
1) Added JPA annotation to UaIdentityManagementPersonDocument.java with entity and table mapping.
2) Defined PersonDocumentExtractor to annotate IdentityManagementPersonDocument to identify which entity class should be used to map table entry
3) Defined IdentityManagementPersonDocumentCustomizer and UAIdentityManagementPersonDocumentCustomizer to define different customized query to KRIM_PERSON_DOCUMENT_T as it's mapping to two different entity class, one vanilla and one UA class.
4) Added UaIdentityManagementPersonDocument.java to Spring JPA path to scan
3. Modified IdentityManagementPersonDocument workflow xml with removing attributes tag which had reference to KFS searching attributes but should not be used for RICE
4. Refactoring edu new class comments

2017-08-15 14:07 UTC, nataliac06 requested changes
Looks great, just one quirk...

2017-08-15 14:07 UTC, nataliac06 commented on rice-middleware/impl/src/main/java/edu/arizona/rice/kim/service/UaUiDocumentService.java
> +package edu.arizona.rice.kim.service;
This is a Service Implementation and I think it should be refactored 
1. moved to ...edu/arizona/rice/kim/service/impl
2. renamed to UaUiDocumentServiceImpl.java

2017-08-16 18:08 UTC, amandazhangm commented on rice-middleware/impl/src/main/java/edu/arizona/rice/kim/service/UaUiDocumentService.java
> +package edu.arizona.rice.kim.service;
Thank you for catching this, Natalia. This code was migrated from rice-2.1-ua-development originally that I didn't look into its package and name. I made recommended code change and will retest, commit and squash.

2017-08-16 18:10 UTC, amandazhangm commented
Close and will create new PR for code review changes.

2017-08-16 18:10 UTC, closed without merging